services:
  web:
    image: nginx:1.27.2
    volumes:
      - ./../www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php:
    build: .
    volumes:
      - ./../www:/var/www/html
  mysql:
    image: mysql:5.7.28
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - ./db_bak:/root/db_bak
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: br
      MYSQL_USER: br
      MYSQL_PASSWORD: bAZDMfbCTDWspTZm
